[package]
name = "ncurses-speed-ball"
version = "0.1.0"
authors = ["administrator"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"